### ISSUE TITLE
Packet Browser Files table scrollbars overlap buttons

### ISSUE THREAD

**Issue by lukebigum** [fmadio/public#167]
Very minor UI issue: on the "Files" (PACKET BROWSER) page, if the number of capture files is greater than the default size of the HTML table, the right hand side vertical scrollbar overlaps part of the delete button (in Chrome 59.0.3071.115 at least).  This makes it ever so slightly harder to delete files.

**Comment by fmadio** [comment]
replay space has been re-located to a different page. There`s now plenty of horz realestate
