### ISSUE TITLE
VOIP default flags

### ISSUE THREAD

**Issue by bigeomaha** [fmadio/public#172]
On the VOIP table, please add the ability to choose default options for filling the table on page load. 

For example, we can choose to only show the last xx hours, only show completed/open/incomplete calls, choose 1000, 5000, etc. Preferably this should be a Web UI so it can be changed easily when doing call research.  When you have more 1000 spoofing attempts in a few hours the incompletes can clog up the view and download 20K results then adding complete filter is not best UIX.

**Comment by fmadio** [comment]
Understood, add a call state checkbox as part of the filter commands

**Comment by fmadio** [comment]
call state filters added:

![image](https://user-images.githubusercontent.com/12390507/28099370-1155ecec-66f7-11e7-87ed-24dada02b7b4.png)

**Comment by fmadio** [comment]
needs regression

**Comment by fmadio** [comment]
added terminate state also. regression added closing
