### ISSUE TITLE
packetscope graphing low pkt counts

### ISSUE THREAD

**Issue by fmadio** [fmadio/public#177]
when issueing packets with a spacing of 100msec apart, packet scope shows some weird graph. Its likely there`s some resolution / rounding going on when total capture is only a few thousand packets.

**Comment by GLEANSUEMASU** [comment]
[64B_100u_1000pkt.zip](https://github.com/fmadio/fmad20_issues/files/1169482/64B_100u_1000pkt.zip)

**Comment by fmadio** [comment]
this is limitation of packet scope, captures need to be >= 1GB for the graph to be detailed enough. captures less than 1GB the resolution of the graph will be extremely poor.
