### ISSUE TITLE
Push support for small time/size updates

### ISSUE THREAD

**Issue by fmadio** [fmadio/public#220]
Need to get push support for 1GB / 5min / 10min etc update frequencies.

**Comment by bigeomaha** [comment]
I concur

**Comment by fmadio** [comment]
added, 1Sec/1M/5M/10M/1H or 100MB/1G/10G options

regression added to remote_push to verify the modes.

**Comment by fmadio** [comment]
let it run in colo for a few days before closing. see if any weirdness shows up

**Comment by fmadio** [comment]
DC security box pushing 1Min PCAP`s with lz4. remote location sometimes runs out of space causing push failures. Cant do anything about that.

![image](https://user-images.githubusercontent.com/12390507/37952961-7f4d7ce6-31dc-11e8-8386-f1093db2d31b.png)

**Comment by fmadio** [comment]
seems good, closing
