### ISSUE TITLE
packetscope top talker 5-tupe

### ISSUE THREAD

**Issue by fmadio** [fmadio/public#251]
add top talkers with full protocol and port info. in addition to the top talkers using ip only

**Comment by fmadio** [comment]
requested again, bumping the priroity

**Comment by rsubramanian31** [comment]
aaron, additionally, is there a way to periodically "pull" this info, say, every 30 secs or 1 min? Something like Top 1000 flows.

**Comment by fmadio** [comment]
thats a bit harder, packet scope is designed for post capture analysis. online realtime analysis will require a different tool, i think pcap2json can provide this exact info

**Comment by fmadio** [comment]
commit dont, helps quite alot to understand taffic segments

![image](https://user-images.githubusercontent.com/12390507/57979495-58ae3280-7a59-11e9-9ab3-e9d522b248d6.png)
