### ISSUE TITLE
API fetch data with time + BPF

### ISSUE THREAD

**Issue by fmadio** [fmadio/public#306]
have stream_http work out which capture to apply a bpf filter based on date/time. Instead of using capture name.

**Comment by fmadio** [comment]
time format is epoch seconds

**Comment by navinsaven** [comment]
Can the time format be in epoch milliseconds instead? Thanks.

**Comment by navinsaven** [comment]
Also, to make it easier to integrate with Grafana (option to download directly from the dashboard via data links), would it be possible to use "from" and "to" instead of "Start" and "Stop" for the time range? Example: &from=1573770589563&to=1573770600185

**Comment by fmadio** [comment]
its no problem. you can request a URL from Grafana to download, that would be so good?

**Comment by navinsaven** [comment]
Yeah. We just use the FMAD API as the URL template and populate the necessary variables using data from the dashboard. That way, we were able to narrow down the traffic we are interested in before initiating a download directly from the Grafana dashboard. Tested by hard coding the capture name in the URL template for now. Once the enhancement to just use time and bpf to download a PCAP is added, we should no longer need to hard code the capture name.

**Comment by fmadio** [comment]
dam... that is cool

**Comment by fmadio** [comment]
do you still need rename the Start/Stop fields to to/from ? cant see the comment anymore

for msec, will add another field to the URI to set the format of the time

**Comment by navinsaven** [comment]
Here's an example specifying the MAC address in BPF. The current URL template requires the capture name to be hard coded and trailing 0s added to convert from epoch ms to ns. We no longer need to rename Start/Stop field.

Current:
http://1.1.1.1/pcap/splittime?StreamName=<capture name>&FilterBPF=ether%20host%20﻿${circuit}﻿﻿&Start=${__from}000000&Stop=${__to}000000

Requested enhancement:
http://1.1.1.1/pcap/splittime?FilterBPF=ether%20host%20﻿${circuit}﻿﻿&Start=${__from}&Stop=${__to}

**Comment by fmadio** [comment]
included from FW:6300+
