### ISSUE TITLE
Packet Scope Filter list missing

### ISSUE THREAD

**Issue by fmadio** [fmadio/public#313]
on all ROMs the default packetscope filter list is missing. need to update with some basic and common filters

**Comment by fmadio** [comment]
default filter list would be 
 
FCS Errors  : frame.fcs == fail
TCP Only : bpf == tcp
UDP only : bpf == udp
DNS only : bpf == udp port 53
port 0 : frame.port == 0
port 1 : frame.port == 1
.
.
port 7

**Comment by dlannan-fmad** [comment]
Will add the same filters from the file split list.
Ahh whoops - updated page and there it is :)

**Comment by dlannan-fmad** [comment]
Is a drop down suitable? Which will effectively create a "starting" block filter with one of the above set?

**Comment by fmadio** [comment]
yup drop down, its setup here, but not working

![image](https://user-images.githubusercontent.com/12390507/73709969-f069c300-4745-11ea-85ce-59fbc1bb8f5a.png)

**Comment by fmadio** [comment]
which is loaded by the file /opt/fmadio/etc/packetscope_filter.lua

feel free to change anything, its all broken currently

**Comment by fmadio** [comment]
hmm some issues tho lol

![image](https://user-images.githubusercontent.com/12390507/73710177-a03f3080-4746-11ea-878a-6fa28ab1a18f.png)

**Comment by dlannan-fmad** [comment]
Ok. I think I have a working version. Fixed a couple of little weird issues.
Its still not entirely right.

**Comment by dlannan-fmad** [comment]
Changed the script.js include to a module. This was a good move there were a number of bugs/issues resolved:
- Some declarations out of order (would have resulted in using some null objects at load)
- Fixed some missing var declarations (only a couple).
- Allows the use of modules now - much nicer for including external js.

**Comment by dlannan-fmad** [comment]
Another note:
- Added mustache for later use. This will allow simple templates (very lightweight) 
- Has powerful for loops and such for html generation. 
I know its not that useful now, but I really think this will help consolidate some of the code from the scripts.js. 
For example: sections using Row += to build html can all be moved to modules with mustache.
Not to be done now. Will make some sample branches to show how it would work.

**Comment by dlannan-fmad** [comment]
Aaron - just checking. Let me know if the module type is a problem. 
The key problem it _may_ cause is compatibility with older browsers (anything about 4yrs or older)

**Comment by dlannan-fmad** [comment]
Odd issue:
- When adding port filters it doesnt clear the filter block (investigating)
All others seem to correctly clear the filter block

**Comment by dlannan-fmad** [comment]
The odd issue:
- When adding a frame.port filter it doesnt clear the internal list of filters properly. 
- The Block list is updated and the frame.port filters appear to append into the list every time.
- Selecting another non frame.port filter, clears the list.

What I added, is when you select a "default filter" then it calls the delete on each row (to ensure the internal list is correct). This appears to work, with the exception of frame.port == fail    -- Weird.

**Comment by dlannan-fmad** [comment]
Ok. I think I have a working version in my dave branch. Will do some more testing to be sure, before putting into staging.

**Comment by fmadio** [comment]
Excellent, wait for the staging PR

**Comment by fmadio** [comment]
checked in staging works well, very cool

pushed to master  closing
