### ISSUE TITLE
PCAP2JSON index creation update

### ISSUE THREAD

**Issue by jbarrett-fmad** [fmadio/public#344]
In order to better manage the indices in ES, it would be useful to create an index per day for P2J. For example here's a comparison of index creation from Logstash vs. P2J:

**Logstash**
output {
  elasticsearch {
        hosts => ["192.168.xxx.xxx:9200"]
        manage_template => true
        index => "fmadio_system_status-%{+yyyy-MM-dd}"
        template => "/etc/logstash/templates/fmadio_system_status_template.json"
        template_name => "fmadio_system_status_template"
        template_overwrite => true
        }

**PCAP2JSON**
["backend"] =
	{
		
		"--index-name pcap2json",
		"--output-espush",
		--"--output-stdout",
		--"--output-null",

		"--es-host 192.168.xxx.xxx:9200",

Need to figure out the lua syntax to replicate the yyyy......etc

**Comment by nsaven** [comment]
You'd have to specify the format during the index creation. For example, `<index-name-{now/d{yyyy.MM.dd|+9}}>`. It has to be URI encoded though so something like this `%3Cindex-name-%7Bnow%2Fd%7Byyyy.MM.dd%7C%2B9%7D%7D%3E`. More details [here](https://www.elastic.co/guide/en/elasticsearch/reference/current/date-math-index-names.html).

You can also automate the rollover and creation of the daily index in Elasticsearch using [Index Lifecycle Management](https://www.elastic.co/guide/en/elasticsearch/reference/current/index-lifecycle-management.html) (ILM) policies.

**Comment by fmadio** [comment]
@nsaven   cool thanks for the info!

**Comment by fmadio** [comment]
dynamic date in the index name provided, closing
