### ISSUE TITLE
Ability to zoom all Sytem Status graphs to same time / zoom level

### ISSUE THREAD

**Issue by eliezerlp** [fmadio/public#40]
Usually I find value in analyzing how capture rates, cache, and temperatures coincide. Being able to link all the graphs together would be great.

I envision two options and a one time sync option:
1) Linked: All zoom and move together
2) Unlinked: All are zoom and move separately (current behavior)
And lastly a "Sync graphs to this graph" button on each graph that takes all graphs to the same time / zoom as the one where the button is pressed. This should only be displayed when the "Unlinked" option is selected.

**Comment by fmadio** [comment]
should be fairly simple to implement.
