### ISSUE TITLE
vlan encapsulated ptp

### ISSUE THREAD

**Issue by fmadio** [fmadio/public#63]
check how sfptp handles vlan tagged ptp packets

**Comment by eliezerlp** [comment]
For sfptpd from a configuration perspective you just have to specify the `interface.vlan` as the interface it should use...

> **6.3 PTP over VLAN**
> Solarflare Enhanced PTP supports PTP packets over tagged 802.1Q Virtual Local Area Network
> (VLAN) interfaces. Users should consult the relevant OS documentation for VLAN configuration
> instructions. Assuming interface eth2.120 is a network interface configured with VLAN tag 120, the
> following example identifies sfptpd VLAN configuration.
> `./sfptpd -ieth2.120 -fconfig/ptp_slave.cfg`

**Comment by fmadio** [comment]
thanks, will update and include the config setting

**Comment by fmadio** [comment]
front end gui part added

fmadio/fmadio20@8bc6249

still needs backend + regression

**Comment by fmadio** [comment]
Gen1 SF only requirement. Been over 1 year so closing. Need to remove the section in the GUI for it
