### ISSUE TITLE
The timestamp of capture name vs 1st split time name for small files

### ISSUE THREAD

**Issue by GLEANSUEMASU** [fmadio/public#72]
The Phenomenon;
The timestamp of display unmatch capturedata time.
See attached picture.

Opertion:
1. Did capture(QUICK).
2. Menu-[FILES]-"FIlename"
3. Select [udp]
4. Select [split_1sec]

Add information
When selected [tcp] ot [port 0], happend same phenomenon.
This phenomenon is happen FW3300 and FW3392.

[20160928_isuue_timestamp_unmatch.zip](https://github.com/fmadio/issues/files/497835/20160928_isuue_timestamp_unmatch.zip)

**Comment by fmadio** [comment]
![image](https://cloud.githubusercontent.com/assets/12390507/18911501/5f1f444e-85b8-11e6-9b09-a2750d2fe2c9.png)

**Comment by fmadio** [comment]
![image](https://cloud.githubusercontent.com/assets/12390507/18911529/8f33bf0c-85b8-11e6-9efc-a758ceb034af.png)

**Comment by fmadio** [comment]
further clarification. the split time as shown in the GUI is not matching the first packet in the downloaded PCAP.

**Comment by fmadio** [comment]
the time in capture stream name is based on capture start time.

time split is based on 1st captured packet.

if there is large delay between capture start to first captured packet, then the GUI can be confusing as the first time split != capture start time. Need to updated split time output to start from capture start time (not 1st captured packet)

**Comment by fmadio** [comment]
narrowed down to the spliter reading the previous captures last chunk, and using that as the starting time stamp.

in this example capture size was 3 chunks, with the length likely wrong for some reason.

**Comment by fmadio** [comment]
probably related to not cycling though the stream indexs. e.g. the previous chunnk has the same streamindex (because its not cycling).

it now cycles though all the stream indexes
